spring:
  datasource:
    url: jdbc:postgresql://localhost/atm
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
token:
  expirationDate: 1200000
  secret: H434HY4HJHJ897FFF